### ISSUE TITLE
Verify that Per Orchestrator metrics work correctly

### ISSUE THREAD

**Issue by leszko** [livepeer/livepeer-monitoring#12]
In https://github.com/livepeer/go-livepeer/issues/2371 we tagged 3 metrics with the orchestrator address and service URI labels. This change may not be backwards-compatible for some queries we use. We need to verify that dashboards using these metrics still works correctly.

**Comment by red-0ne** [comment]
Searching into this repo's codebase, the patterns `transcode_overall_latency_seconds`, `segment_transcoded_all_appeared_total` and `segment_transcoded_unprocessed_total` are found in different locations such as:
* `livepeer_transcode_overall_latency_seconds_bucket  found multiple times like  "expr": "histogram_quantile(0.95, sum(rate(livepeer_transcode_overall_latency_seconds_bucket[1m])) by (le))" `
* `livepeer_transcode_overall_latency_seconds_sum found multiple times in expressions like "expr": "sum(rate(livepeer_transcode_overall_latency_seconds_sum{node_type=\"bctr\"}[1m])) by (instance) / sum(rate(livepeer_transcode_overall_latency_seconds_count{node_type=\"bctr\"}[1m])) by (instance)"`

The other metrics are found too. But noting that all of them use `sum(rate(...))`  or `sum(...)` just like how it's been fixed in https://github.com/livepeer/stream-tester/pull/152/files.

So the change mentioned should not affect the current views.
